version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "glue2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jidmwm5vyyhm"
s3_prefix = "glue2"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TargetDynamoDBTable=\"Employee\" TargetRegion=\"eu-west-1\" TargetAccountNumber=\"572463205119\" TargetRoleName=\"TargetDynamoRole\" SourceDynamoDBTable=\"Employee\" WorkerType=\"G.2X\" NumberOfWorkers=\"145\" JobName=\"initial_load1\""

